# frontend/Dockerfile.ci
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

# Copy folder build (dist) từ GitLab Runner vào container
COPY ./dist /usr/share/nginx/html

# Copy file cấu hình Nginx (File nginx.conf mà ta đã sửa ở các bước trước)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
