server {
    listen 80;
    server_name localhost;

    # Đường dẫn gốc tới file build React
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Cấu hình quan trọng nhất cho React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tắt log access để đỡ rác, chỉ hiện lỗi
    error_log /var/log/nginx/error.log warn;
    access_log off;
}